### ISSUE TITLE
DistServe是否支持异构推理？

### ISSUE THREAD

**Issue by RobertLou** [LLMServe/DistServe#34]
我的机器有两张卡，分别是A40和A30，A40拥有48G显存，A30拥有24G显存，使用的模型是Llama-2-7b-chat-hf，精度为fp16。按计算来说两卡应该都能放下，但作为decode机器的A30会报OOM错误。

**Comment by RobertLou** [comment]
好吧，我查到SwiftTransformer中的报错了，看上去确实必须Nvlink？如果走PCIe就得先到CPU上数据转一圈？

**Comment by ddqspace-xyz** [comment]
意思是运行DistServe环境，必须是支持NVlink的GPU才可以？

**Comment by RobertLou** [comment]
> 意思是运行DistServe环境，必须是支持NVlink的GPU才可以？

是的吧，其他的互联方式Infiniband和高速网卡连接什么的我不了解，从代码上来看主要是cudaIpcOpenMemHandle和cudaMemcpy2DAsync这两个接口，我这边两卡没有直接互连就会报错。
