### ISSUE TITLE
[Profile] How to use nsight to profile CUDA execution information

### ISSUE THREAD

**Issue by vincentccc** [LLMServe/DistServe#36]
I use nsys cli to profile offline and serving, and found some problem

1. The cuda HW info  cannot be traced when I use example/offline.py
2. Prefill instance cudaHW info cannot be trace when use nsys to start a serving, only decode instance
3. Use nsys in ray actor to profile single Process, still cannot trace cudaHW.

Can I ask for how to profile correctly?

**Comment by interestingLSY** [comment]
DistServe uses [Ray](https://www.ray.io/). If you want to profile it by nsys,you may need to refer to [Ray's Document](https://docs.ray.io/en/latest/ray-observability/user-guides/profiling.html)

**Comment by vincentccc** [comment]
Thanks for your reply. I found the report seems make sense when I issue more requests
