### ISSUE TITLE
cmake error when running "cmake -B build" in swiftTransformer

### ISSUE THREAD

**Issue by KylinC** [LLMServe/DistServe#6]
-- Using the multi-header code from /home/fx/cql/DistServe/SwiftTransformer/build/_deps/json-src/include/
-- Configuring done (30.8s)
CMake Error at src/csrc/kernel/CMakeLists.txt:23 (add_library):
  No SOURCES given to target: xformers_autogen_impl

**Comment by interestingLSY** [comment]
Please run `git submodule update --init --recursive` after cloning the `SwiftTransformer` repository.

By the way, it is encouraged to share your solution for others if you have figured out it for your issue.
